blog/urls.py
from django.urls import path
from .views import * 

app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),
    # path('<int::year>/<int::month>/<int::day>/<slug::post>',post_detail,name='post_detail'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',post_detail, name='post_detail'),
    # path('<int:id>/<slug:post>',post_detail,name='post_detail'),
    path('<int:post_id>/share/', post_share, name='post_share'),
]
#{% url 'post_detail' id=post.id slug=post.slug %}

cabinet/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'cabinet'
urlpatterns = [
    path('cabinet/<str:slug>/', MixinDetailCabinet.as_view(), name='cabinet_main_page'),#TODO передать название компании
    path('cabinet/master/<str:slug>/',DetailCabinetMasters.as_view(),name='cabinet_masters_company_url'),
    path('information/<str:slug>/', BaseInformation.as_view(), name='base_information_new'),
    path('orders/<str:slug>/', BaseCompanyOrders.as_view(), name='base_company_orders_new'),
    path('masters/<str:slug>/', BaseCompanyMasters.as_view(), name='base_company_masters_new'),
    path('foto/<str:slug>/', BaseCompanyFoto.as_view(), name='base_company_foto_new'),
    path('description/<str:slug>/', BaseCompanyDescription.as_view(), name='base_company_description_new'),
    re_path(r'base_information/$',BaseInformation.as_view(), name='base_information'),
    re_path(r'base_company_orders/$',BaseCompanyOrders.as_view(),name='base_company_orders'),
    re_path(r'base_company_masters/$',CreateMaster.as_view(),name='base_company_masters'),
    re_path(r'base_company_foto/$',BaseCompanyFoto.as_view(), name='base_company_foto'),
    re_path(r'base_company_description/$',CreteOperation.as_view(),name='base_company_description'),
    re_path(r'orders/$', OrderCabinet.as_view(), name='orders'),
    re_path(r'profile/$', ProfileCabinet.as_view(), name='profile'),
    re_path(r'timetable/$', TimetableCabinet.as_view(), name='timetable'),
    re_path(r'delete_masters_form/$',Delete_masters_form.as_view(), name='delete_master_form'),
    re_path(r'create_operation/$', CreteOperationMaster.as_view(), name='profile'),
]

web_project/urls.py
"""
    Этот код тянет ссылается на hello/urls.py django.urls.include, 
    в котором сохраняются маршруты приоложения, содержащиеся в приложении. Это разделение полезно
    когда проект содержит несколько приложений
"""

from django.contrib import admin
from django.urls import include, path 
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns 
from django.conf import settings

#from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("flesh.urls")),
    path('main_cabinet/', include("cabinet.urls", namespace='main_cab')),
    path('blog/',include("blog.urls",namespace='blog')),
    path('captcha/', include('captcha.urls')), #модуль с каптчей его не видно в основных приложения 
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

cabinet/models.py
from django.db import models

cabinet/views.py
# -*- coding: utf-8 -*-
from django.views.generic import View,TemplateView
from django.shortcuts import render, redirect, render_to_response, get_object_or_404, reverse
from flesh.models import Company, Masters, Operations, OperationsDetailNas, Order #TODO зарефакторить работу с моделями 
from flesh.forms import AdministrationForm, LoginForm,Logform,LoginForm,CompanyForm
from .forms import ForingMastersCabinetForm, CompanyCabinetForm, MastersForm, MastresFoto, CreateOperations, DetailCreateOperations
from django.contrib.auth.models import Group, User
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.template import RequestContext


class Delete_masters_form(View):
    model = Order
    template_name = 'cabinet/includes/delete_masters_form.html'

    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            if request.method =='POST':
                try:
                    Masters.objects.get(slug=request.POST['master']).delete()
                except:
                    return HttpResponse('ne ok')
                # masta = request.user.groups.all()
                # obj = get_object_or_404(Company, slug__iexact=masta[0])
                # masters= obj.masters_set.all()
                
                # context = self.get_context_data(**kwargs)
                # context['company'] = obj
                # if masters is not None:  
                #     context['masters'] = masters
            return HttpResponse('ok')



class OrderCabinet(TemplateView):
    model = Order
    template_name = 'cabinet/includes/timetable.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
             if request.method =='GET':
                return render_to_response(self.template_name)

    @csrf_protect
    def post(self, request, *args, **kwargs):
        print(request)
        return HttpResponse('ok')


class ProfileCabinet(TemplateView):
    model = Masters
    template_name = 'cabinet/includes/master_cabinet/profile_master.html'

    def get(self,request, *args, **kwargs):
        if request.user.is_authenticated:
            master = request.user.groups.all()
            #form = ForingMastersCabinetForm(request.POST, request.FILES)
            obj = get_object_or_404(self.model, slug__iexact=master[0])
            operations = obj.operations_set.all()            
            all_operations = Operations.objects.all()

            context = self.get_context_data(**kwargs)
            context['master'] = obj
            context['servises'] = operations
            context['operations'] = all_operations

            return self.render_to_response(context)

class CreteOperationMaster(View):
    def post(self, request):
        if request.method == "POST":
            
            create_operations = DetailCreateOperations(request.POST)
            if create_operations.is_valid():
                create_operations.clean()
                try:
                    obj = get_object_or_404(Masters, slug__iexact=request.POST['slug'])
                    opr = Operations.objects.filter(name_operations)
                except:
                    return redirect('administration_url')
                new_oper = create_operations.cleaned_data['name'].lower()
                
                if Operations.objects.filter(name_operations='new_oper'):
                    errors = 'ОШИБКА проверьте пожалуйста данные возможно такая услуга присутствует в базе'
                else:
                    oper = OperationsDetailNas(cash=create_operations.cleaned_data['cash'],)
                    errors = ''
            else:
                errors = 'ОШИБКА проверьте пожалуйста данные'       
            return JsonResponse({'new_oper':new_oper, 'errors':errors})
        else: 
            return redirect('administration_url')


class TimetableCabinet(TemplateView):
    model = Order
    template_name ='cabinet/includes/timetable.html'

    def get(self,request, *args, **kwargs):
        if request.user.is_authenticated:
             if request.method =='GET':
                # obj = get_object_or_404(self.model, slug__iexact=slug)
                return render_to_response(self.template_name)

    @csrf_protect
    def post(self, request, *args, **kwargs):
        return HttpResponse('ok')


#Основа под главную страницу, придётся подразбить для Ajax 
class MixinDetailCabinet(TemplateView):
    model=Company
    template_name ='cabinet/base_cabinet.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            masta = request.user.groups.all()
            obj = get_object_or_404(self.model, slug__iexact=masta[0])
            try:
                masters = Masters.objects.filter(company=obj)
            except:
                masters=None
            mastersform = MastersForm(self.request.GET or None)
            fotoform    = MastresFoto(self.request.GET or None)
            companyform = CompanyForm(self.request.GET or None)
            prob_form   = ForingMastersCabinetForm(self.request.POST or None)

            context = self.get_context_data(**kwargs)
            context['mastersform']               = mastersform
            context['fotoform']                  = fotoform
            context['companyform']               = companyform
            context['prob_form']                 = prob_form
            context[self.model.__name__.lower()] = obj
            if masters is not None:
                context['masters'] = masters
            return self.render_to_response(context)
        else:
            pass
            #return HttpResponseRedirect('notforyou') #TODO Сделать глабальную обработку ошибок 

    def post(self, request, *args, **kwargs):
        form_class = MastersForm
        template_name = 'cabinet/base_cabinet.html'
        success_url = 'cabinet/'

        mastersform = MastersForm()
        fotoform    = MastresFoto()

        masta = request.user.groups.all()
        obj = get_object_or_404(self.model, slug__iexact=masta[0])
        try: 
            masters = Masters.objects.filter(company_id=obj.id)
        except:
            masters=None
        
        if request.method=='POST' and 'createmasters' in request.POST:
            mastersform = form_class(request.POST)
            if mastersform.is_valid():
                mastersform.save(obj)
                try:
                    masters=Masters.objects.filter(company=obj)
                except:
                    masters=None
                mastersform.clean()
                return self.render_to_response(self.get_context_data(mastersform=mastersform,fotoform=fotoform,masters=masters ,company=obj ))
            else:
                mastersform.clean()
                erors_m='Не верная форма, возможно пользователь с таким номером уже существует'
                return self.render_to_response(self.get_context_data(erors_m=erors_m, mastersform=mastersform,fotoform=fotoform, masters=masters,company=obj)
            )
        if request.method=='POST' and 'e' in request.POST:
            return redirect('administration_url')

# TODO Сделать разделение пользователей на профессии 
class DetailCabinetMasters(TemplateView):
    model=Company
    template_name ='cabinet/base_cabinet_masters.html'
    
    def get(self,request, slug,*args, **kwargs):
        if request.user.is_authenticated:
            if slug is not '':
                masta = request.user.groups.all()
                obj = get_object_or_404(self.model, slug__iexact=masta[0])
                mastersform = MastersForm(self.request.GET or None)
                fotoform = MastresFoto(self.request.GET or None)
                context = self.get_context_data(**kwargs)
                context['mastersform'] = mastersform
                context['fotoform']    = fotoform
                context['masters']     = get_object_or_404(Masters, slug__iexact=slug)
                context[self.model.__name__.lower()] = obj
                return self.render_to_response(context)
            else:
                return self.render_to_response(context)
        else:
            return redirect('administration_url')
    
    def post(self, request, *args, **kwargs):
        pass
        # form_class = MastersForm
        # template_name = 'flesh/base_cabinet.html'
        # success_url = 'cabinet/'

        # mastersform = MastersForm()
        # prostoform  = ProstForm()
        # fotoform    = MastresFoto()

        # masta = request.user.groups.all()
        # obj = get_object_or_404(self.model, slug__iexact=masta[0])
        # try: 
        #     masters = Masters.objects.filter(company_id=obj.id)
        # except:
        #     masters=None

class BaseInformation(TemplateView):
    model=Company
    template_name ='cabinet/includes/base_cabinet/base_cabinet_information.html'

    def get(self, request,*args, **kwargs):
        if request.user.is_authenticated:
            masta = request.user.groups.all()
            obj = get_object_or_404(self.model, slug__iexact=masta[0])
            context = self.get_context_data(**kwargs)
            context['company'] = obj
            return self.render_to_response(context)
        else:
            return redirect('administration_url')

    def post(self, request):
        pass


class BaseCompanyOrders(TemplateView):
    model=Company
    template_name ='cabinet/includes/base_cabinet/base_company_orders.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            masta = request.user.groups.all()
            obj = get_object_or_404(self.model, slug__iexact=masta[0])
            masters= obj.masters_set.all() #TODO Проверить отправляется ли пустной список
            orders = obj.order_set.all() #все заказы компании

cabinet/templates/cabinet/includes/create_masters_form.html
        <p>
            <a class="btn btn-success" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                Создать нового мастера
            </a>
        </p>
        <div class="collapse" id="collapseExample">
            <div class="card card-body">
                <div class="alert alert-danger" role="alert" id='error_m' hidden>
                    <div class='errors_floor' id='errors' >
                        Возникли проблемы при отправке формы, проверьте введенные данные.
                    </div>
                </div>
                Имя мастера<br>
                <input class="form-control" id="nameMaster"><br> 
                {% comment %}<small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                {{ mastersform.name_m }}{% endcomment %}
                Номер мастера<br>
                {% comment %} {{mastersform.number_m}} {% endcomment %}
                <input class="form-control" id="numberMaster">
                <br><p><button class="btn btn-success getres" id='{{company.slug}}' onclick="return create_masters(this.id);">Создать</button></p>
                <p>Нажимая на кнопку, вы даете согласие на обработку своих персональных данных. <a href="#" class="badge badge-light">Пользовательское соглашение</a></p>
            </div>
        </div>

cabinet/templates/cabinet/includes/delete_masters_form.html
<div class='row mb-3'><div class='col-4'>Имя мастра</div><div class='col-2'>Процент</div><div class='col-2'>Обслужено</div><div class='col-2'></div><div class='col-2'><span class='statistic'>Удаление</span></div></div>
    {% if masters is not None %}
        {% for master in masters %}
            <div class='row '>
                <div class='col-4'>
                    <b><a href="{% url 'cabinet:cabinet_masters_company_url' slug=master.slug%}" style="text-decoration: none; color:black;"> {{master.name_m |truncatewords:30}} </a></b>
                </div>
                <div class='col-2'>
                    <span class='statistics'><p>50%</p><span>
                </div>
                <div class='col-2'>
                    <span class='statistics'><p>50 чел.</p><span> 
                </div>
                <div class='col-2'>
                    <span class='statistics'><p>Что-то</p><span>
                </div>
                <div class='col-2'>
                    <a class='close_master'  id='{{master.slug}}' onclick="return delete_masters(this.id);"></a>
                </div> 
            </div>
        {% endfor %}
    {% endif %}
                                

cabinet/templates/cabinet/includes/timetable.html
<div class="table-wrap">
  <!--<div class="description">Данная панель ещё находится в разработке</div> -->
  <div class="right-wrap defaultscroll">
    <div class="right-column"><div class="date-box">16.06.2020 (Вт)</div>
      <form class="form-select">
        <!--<button class='btn'>Показать</button>-->
        <div class='form_grup'>
          <div class='box-date'>

            <div class='form-group row m-1'>
              <div class="col-6 ">
                <input type="time" class="form-control shadow bg-white border-0 ">
              </div>
              <div class="col-6 ">
                  <input type="time" class="form-control shadow bg-white border-top-0 border border-2 ml-0" placeholder="Время до">
              </div>
            </div>

            <div class='form-row m-2'>
              <div class="col-12">
                <input class='form-input' type="text" id="email" required autocomplete="off" placeholder='Процедура'>
              </div>
            </div>
            <div class='form-row m-2'>
              <div class="col-12">
                <input class='form-input' type="text" id="email" required autocomplete="off" placeholder='ФИО'>
              </div>
            </div>
            

            <div class='row'>
              <div class='col-2'></div>
              <div class='col-8'>
                <button class='btn_select_menu'>Записать клиента</button>
              </div>
              <div class='col-2'></div>
            </div>
          </div>
        </div>
      </form>
      <div class='zap-block shadow-lg p-3 mb-3 bg-white rounded'>
        <div class="card-header"><p><div align="left"><b>12:30</b> Стрижка </div></p></div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item" align="left"><b>Телефон:</b> 89210607568</li>
          <li class="list-group-item" align="left"><b>ФИО</b>Таран Юрий Петрович</li>
        </ul>
      </div>
      <div class='zap-block shadow-lg p-3 mb-3 bg-white rounded'>
        <div class="card-header"><p><div align="left"><b>12:30</b> Стрижка </div></p></div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item" align="left"><b>Телефон:</b> 89210607568</li>
          <li class="list-group-item" align="left"><b>ФИО</b>Таран Юрий Петрович</li>
        </ul>
      </div>
    </div>

    <div class="right-column"><div class="date-box">17.06.2020 (Ср)</div> Нет записей </div>
    <div class="right-column"><div class="date-box">18.06.2020 (Чт)</div> Нет записей </div>
    <div class="right-column"><div class="date-box">19.06.2020 (Пт)</div> Нет записей </div>
    <div class="right-column"><div class="date-box">20.06.2020 (Суб)</div> Нет записей </div>
    <div class="right-column"><div class="date-box">21.06.2020 (Воскр)</div> Нет записей </div>
    <div class="right-column"><div class="date-box">22.06.2020 (Пн)</div> Нет записей </div>
  </div>
</div>