blog/urls.py
from django.urls import path
from .views import * 

app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),
    # path('<int::year>/<int::month>/<int::day>/<slug::post>',post_detail,name='post_detail'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',post_detail, name='post_detail'),
    # path('<int:id>/<slug:post>',post_detail,name='post_detail'),
    path('<int:post_id>/share/', post_share, name='post_share'),
]
#{% url 'post_detail' id=post.id slug=post.slug %}

cabinet/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'cabinet'
urlpatterns = [
    path('cabinet/<str:slug>/', MixinDetailCabinet.as_view(), name='cabinet_main_page'),#TODO передать название компании
    path('cabinet/master/<str:slug>/',DetailCabinetMasters.as_view(),name='cabinet_masters_company_url'),
    path('information/<str:slug>/', BaseInformation.as_view(), name='base_information_new'),
    path('orders/<str:slug>/', BaseCompanyOrders.as_view(), name='base_company_orders_new'),
    path('masters/<str:slug>/', BaseCompanyMasters.as_view(), name='base_company_masters_new'),
    path('foto/<str:slug>/', BaseCompanyFoto.as_view(), name='base_company_foto_new'),
    path('description/<str:slug>/', BaseCompanyDescription.as_view(), name='base_company_description_new'),
    re_path(r'base_information/$',BaseInformation.as_view(), name='base_information'),
    re_path(r'base_company_orders/$',BaseCompanyOrders.as_view(),name='base_company_orders'),
    re_path(r'base_company_masters/$',CreateMaster.as_view(),name='base_company_masters'),
    re_path(r'base_company_foto/$',BaseCompanyFoto.as_view(), name='base_company_foto'),
    re_path(r'base_company_description/$',CreteOperation.as_view(),name='base_company_description'),
    re_path(r'orders/$', OrderCabinet.as_view(), name='orders'),
    re_path(r'profile/$', ProfileCabinet.as_view(), name='profile'),
    re_path(r'timetable/$', TimetableCabinet.as_view(), name='timetable'),
    re_path(r'delete_masters_form/$',Delete_masters_form.as_view(), name='delete_master_form'),
    re_path(r'create_operation/$', CreteOperationMaster.as_view(), name='profile'),
]

web_project/urls.py
"""
    Этот код тянет ссылается на hello/urls.py django.urls.include, 
    в котором сохраняются маршруты приоложения, содержащиеся в приложении. Это разделение полезно
    когда проект содержит несколько приложений
"""

from django.contrib import admin
from django.urls import include, path 
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns 
from django.conf import settings

#from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("flesh.urls")),
    path('main_cabinet/', include("cabinet.urls", namespace='main_cab')),
    path('blog/',include("blog.urls",namespace='blog')),
    path('captcha/', include('captcha.urls')), #модуль с каптчей его не видно в основных приложения 
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

cabinet/models.py
from django.db import models

cabinet/views.py
# -*- coding: utf-8 -*-
from django.views.generic import View,TemplateView
from django.shortcuts import render, redirect, render_to_response, get_object_or_404, reverse
from flesh.models import Company, Masters, Operations, OperationsDetailNas, Order #TODO зарефакторить работу с моделями 
from flesh.forms import AdministrationForm, LoginForm,Logform,LoginForm,CompanyForm
from .forms import ForingMastersCabinetForm, CompanyCabinetForm, MastersForm, MastresFoto, CreateOperations, DetailCreateOperations
from django.contrib.auth.models import Group, User
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.template import RequestContext


class Delete_masters_form(View):
    model = Order
    template_name = 'cabinet/includes/delete_masters_form.html'

    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            if request.method =='POST':
                try:
                    Masters.objects.get(slug=request.POST['master']).delete()
                except:
                    return HttpResponse('ne ok')
                # masta = request.user.groups.all()
                # obj = get_object_or_404(Company, slug__iexact=masta[0])
                # masters= obj.masters_set.all()
                
                # context = self.get_context_data(**kwargs)
                # context['company'] = obj
                # if masters is not None:  
                #     context['masters'] = masters
            return HttpResponse('ok')



class OrderCabinet(TemplateView):
    model = Order
    template_name = 'cabinet/includes/timetable.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
             if request.method =='GET':
                return render_to_response(self.template_name)

    @csrf_protect
    def post(self, request, *args, **kwargs):
        print(request)
        return HttpResponse('ok')


class ProfileCabinet(TemplateView):
    model = Masters
    template_name = 'cabinet/includes/master_cabinet/profile_master.html'

    def get(self,request, *args, **kwargs):
        if request.user.is_authenticated:
            master = request.user.groups.all()
            #form = ForingMastersCabinetForm(request.POST, request.FILES)
            obj = get_object_or_404(self.model, slug__iexact=master[0])
            operations = obj.operations_set.all()            
            all_operations = Operations.objects.all()

            context = self.get_context_data(**kwargs)
            context['master'] = obj
            context['servises'] = operations
            context['operations'] = all_operations

            return self.render_to_response(context)

class CreteOperationMaster(View):
    def post(self, request):
        if request.method == "POST":
            
            create_operations = DetailCreateOperations(request.POST)
            if create_operations.is_valid():
                create_operations.clean()
                try:
                    obj = get_object_or_404(Masters, slug__iexact=request.POST['slug'])
                    opr = Operations.objects.filter(name_operations)
                except:
                    return redirect('administration_url')
                new_oper = create_operations.cleaned_data['name'].lower()
                
                if Operations.objects.filter(name_operations='new_oper'):
                    errors = 'ОШИБКА проверьте пожалуйста данные возможно такая услуга присутствует в базе'
                else:
                    oper = OperationsDetailNas(cash=create_operations.cleaned_data['cash'],)
                    errors = ''
            else:
                errors = 'ОШИБКА проверьте пожалуйста данные'       
            return JsonResponse({'new_oper':new_oper, 'errors':errors})
        else: 
            return redirect('administration_url')


class TimetableCabinet(TemplateView):
    model = Order
    template_name ='cabinet/includes/timetable.html'

    def get(self,request, *args, **kwargs):
        if request.user.is_authenticated:
             if request.method =='GET':
                # obj = get_object_or_404(self.model, slug__iexact=slug)
                return render_to_response(self.template_name)

    @csrf_protect
    def post(self, request, *args, **kwargs):
        return HttpResponse('ok')


#Основа под главную страницу, придётся подразбить для Ajax 
class MixinDetailCabinet(TemplateView):
    model=Company
    template_name ='cabinet/base_cabinet.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            masta = request.user.groups.all()
            obj = get_object_or_404(self.model, slug__iexact=masta[0])
            try:
                masters = Masters.objects.filter(company=obj)
            except:
                masters=None
            mastersform = MastersForm(self.request.GET or None)
            fotoform    = MastresFoto(self.request.GET or None)
            companyform = CompanyForm(self.request.GET or None)
            prob_form   = ForingMastersCabinetForm(self.request.POST or None)

            context = self.get_context_data(**kwargs)
            context['mastersform']               = mastersform
            context['fotoform']                  = fotoform
            context['companyform']               = companyform
            context['prob_form']                 = prob_form
            context[self.model.__name__.lower()] = obj
            if masters is not None:
                context['masters'] = masters
            return self.render_to_response(context)
        else:
            pass
            #return HttpResponseRedirect('notforyou') #TODO Сделать глабальную обработку ошибок 

    def post(self, request, *args, **kwargs):
        form_class = MastersForm
        template_name = 'cabinet/base_cabinet.html'
        success_url = 'cabinet/'

        mastersform = MastersForm()
        fotoform    = MastresFoto()

        masta = request.user.groups.all()
        obj = get_object_or_404(self.model, slug__iexact=masta[0])
        try: 
            masters = Masters.objects.filter(company_id=obj.id)
        except:
            masters=None
        
        if request.method=='POST' and 'createmasters' in request.POST:
            mastersform = form_class(request.POST)
            if mastersform.is_valid():
                mastersform.save(obj)
                try:
                    masters=Masters.objects.filter(company=obj)
                except:
                    masters=None
                mastersform.clean()
                return self.render_to_response(self.get_context_data(mastersform=mastersform,fotoform=fotoform,masters=masters ,company=obj ))
            else:
                mastersform.clean()
                erors_m='Не верная форма, возможно пользователь с таким номером уже существует'
                return self.render_to_response(self.get_context_data(erors_m=erors_m, mastersform=mastersform,fotoform=fotoform, masters=masters,company=obj)
            )
        if request.method=='POST' and 'e' in request.POST:
            return redirect('administration_url')

# TODO Сделать разделение пользователей на профессии 
class DetailCabinetMasters(TemplateView):
    model=Company
    template_name ='cabinet/base_cabinet_masters.html'
    
    def get(self,request, slug,*args, **kwargs):
        if request.user.is_authenticated:
            if slug is not '':
                masta = request.user.groups.all()
                obj = get_object_or_404(self.model, slug__iexact=masta[0])
                mastersform = MastersForm(self.request.GET or None)
                fotoform = MastresFoto(self.request.GET or None)
                context = self.get_context_data(**kwargs)
                context['mastersform'] = mastersform
                context['fotoform']    = fotoform
                context['masters']     = get_object_or_404(Masters, slug__iexact=slug)
                context[self.model.__name__.lower()] = obj
                return self.render_to_response(context)
            else:
                return self.render_to_response(context)
        else:
            return redirect('administration_url')
    
    def post(self, request, *args, **kwargs):
        pass
        # form_class = MastersForm
        # template_name = 'flesh/base_cabinet.html'
        # success_url = 'cabinet/'

        # mastersform = MastersForm()
        # prostoform  = ProstForm()
        # fotoform    = MastresFoto()

        # masta = request.user.groups.all()
        # obj = get_object_or_404(self.model, slug__iexact=masta[0])
        # try: 
        #     masters = Masters.objects.filter(company_id=obj.id)
        # except:
        #     masters=None

class BaseInformation(TemplateView):
    model=Company
    template_name ='cabinet/includes/base_cabinet/base_cabinet_information.html'

    def get(self, request,*args, **kwargs):
        if request.user.is_authenticated:
            masta = request.user.groups.all()
            obj = get_object_or_404(self.model, slug__iexact=masta[0])
            context = self.get_context_data(**kwargs)
            context['company'] = obj
            return self.render_to_response(context)
        else:
            return redirect('administration_url')

    def post(self, request):
        pass


class BaseCompanyOrders(TemplateView):
    model=Company
    template_name ='cabinet/includes/base_cabinet/base_company_orders.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            masta = request.user.groups.all()
            obj = get_object_or_404(self.model, slug__iexact=masta[0])
            masters= obj.masters_set.all() #TODO Проверить отправляется ли пустной список
            orders = obj.order_set.all() #все заказы компании

cabinet/templates/cabinet/base_cabinet.html
{%extends 'base_page.html'%}
{%load static%}
{% block head %}

    <link rel="stylesheet" href="{% static 'cabinet/css/cabinet.css' %}">
    <link rel="stylesheet" href="{% static 'cabinet/css/closer.css' %}">
    <!--<link rel="stylesheet" href="{% static 'cabinet/css/modal_window.css' %}">-->
    <link rel="stylesheet" href="{% static 'cabinet/css/modal_window2.css' %}">
    <link rel="stylesheet" href="{% static 'cabinet/css/new_style.css' %}">

{% csrf_token %}
{% endblock head %}
{% block body %}
    {% csrf_token %}
    <div class="main_bg bg-secondary">
    <div class='row no-gutters'>
        <div class='col-3 bg-secondary d-none d-md-block sticky-top' style='height:100vh;'>
            <div class="list-group sticky-top" id="list-tab" role="tablist">
                <a class="btn" id="list-profile-btn" style="color:white;" href="{% url 'company_detail_url' slug=company.slug %}" aria-controls="profile"><b>Компания {{company.name}}</b></a> 
                <a class=" btn list-group-item list-group-item-action bg-secondary border-0" style="color:white;" id="list-profile-list" role="tab" href="{% url 'cabinet:base_information_new' slug=company.slug%}" aria-controls="clients">Информация </a> 
                <a class="list-group-item list-group-item-action bg-secondary border-0" style="color:white;" id="list-messages-list" role="tab" href="{% url 'cabinet:base_company_orders_new' slug=company.slug%}" aria-controls="clients">Заказы <span class="badge badge-light">15</span></a>
                <a class="list-group-item list-group-item-action bg-secondary border-0" style="color:white;" id="list-masters-list" role="tab" href="{% url 'cabinet:base_company_masters_new' slug=company.slug%}" aria-controls="masters">Мастера</a>
                <a class="list-group-item list-group-item-action bg-secondary border-0" style="color:white;" id="list-foto-list"  role="tab" href="{% url 'cabinet:base_company_foto_new' slug=company.slug%}" aria-controls="foto">Фото компании</a>
                <a class="list-group-item list-group-item-action bg-secondary border-0" style="color:white;" id="list-description-list" role="tab" href="{% url 'cabinet:base_company_description_new' slug=company.slug%}" aria-controls="description">Описание компании</a>
            </div>
        </div>

        <div class='col-12 col-md-9 bg-white'>
            <div class='content ' id='content'>
                {% block cabinet_content %}
                {% endblock cabinet_content %}
            </div>
        </div>
    </div>
    </div>

    <div class="fixed-bottom">
        <div class='row d-sm-block d-md-none h-50'>
            <div class='col-12 bg-light'>
                <ul class="nav justify-content-around">
                    <li class="nav-item">
                    <img src="{%static 'flesh/svg/image.svg'%}" data-toggle="tab" href="#list-profile" style="max-width:2rem;" class="card-img-top align-self-center" alt="No img">
                    </li>
                    <li class="nav-item">
                        <img src="{%static 'flesh/svg/master.svg'%}" data-toggle="tab" href="#list-masters" style="max-width:2rem;" class="card-img-top align-self-center" alt="No img">
                    </li>
                    <li class="nav-item">
                        <img src="{%static 'flesh/svg/message.svg'%}" style="max-width:2rem;" class="card-img-top align-self-center" alt="No img">
                    </li>
                    <li class="nav-item">
                        <img src="{%static 'flesh/svg/description.svg'%}" style="max-width:2rem;" class="card-img-top align-self-center" alt="No img">
                    </li>
                </ul>
            </div>
        </div>
    </div>

<script src="{% static 'cabinet/jquery-3.4.1/jquery-3.4.1.min.js' %}"></script>
<!--<script>$('#content').load("{% url 'cabinet:base_information' %}?content=");</script>-->
<script src="{% static 'cabinet/js/base_cabinet.js' %}"></script>
<script src="{% static 'cabinet/js/scroll_1.js' %}"></script>

{% endblock body %}
{% block footer %}
{% endblock footer %}

cabinet/templates/cabinet/base_cabinet_masters.html
{%extends 'base_page.html'%}
{%load static%}
{% block head %}
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'cabinet/css/cabinet.css' %}">
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Roboto'>
    <link rel="stylesheet" href="{% static 'cabinet/css/new_style.css' %}">
    <style>
        form {
            max-width: 40vw;
            display: flex;
            flex-direction: column;
        }

        form label {
            font-family: "Open Sans", sans-serif;
            font-size: 1.2rem;
            margin-bottom: 12px;
        }

        form input {
            height: 40px;
            padding: 5px;
            font-size: 1rem;
        }

        form input:focus {
            outline: none;
        }
    </style>
    <!--<link rel='stylesheet' href='https://opensource.keycdn.com/fontawesome/4.6.3/font-awesome.min.css'>-->
{% endblock head %}
{% block body %}
<div class="main_bg bg-secondary">
    <div class='row no-gutters'>
        <div class='col-3 bg-secondary d-none d-md-block sticky-top' style='height:100vh;'>
            <!--<div class="list-group sticky-top" id="list-tab" role="tablist">-->
            <a class="btn" id="list-profile-btn" style="color:white;" href="{% url 'company_detail_url' slug=company.slug%}" aria-controls="profile"><b>Мастер {{masters.name_m}}</b></a>
            <a class="list-group-item list-group-item-action bg-secondary sticky-top border-0" style="color:white; width:100%;" id="master_orders" data-toggle="list" type="button" href="#list-message" role="tab" aria-controls="clients">Заказы</a>
            <a class="list-group-item list-group-item-action bg-secondary sticky-top border-0" style="color:white;" id="master_profile" data-toggle="list" href="#list-profile" role="tab" aria-controls="clients">Профиль</a>
            <a class="list-group-item list-group-item-action bg-secondary sticky-top border-0" style="color:white;" id="master_timetable" data-toggle="list" href="#list-chart" role="tab">График</a>
            <!--</div>-->
        </div>

        <div class='col-12 col-md-9 bg-white' id='main_roomspace'>
            <div class='col-1'></div>
            <div class='col-10'>
                <div id="content"></div>
            </div>
            <div class='col-1'></div>
        </div>
    </div>
</div>
<div class="fixed-bottom">
    <div class='row d-sm-block d-md-none h-50'>
        <div class='col-12 bg-light p-2'>
            <ul class="nav justify-content-around">
                <li class="nav-item">
                <img src="{%static 'flesh/svg/icon_masters.svg'%}" data-toggle="tab" href="#list-message" style="max-width:2rem;" class="card-img-top align-self-center" alt="No img">
                </li>
                <li class="nav-item">
                    <img src="{%static 'flesh/svg/button_masters.svg'%}" data-toggle="tab" href="#list-chart" style="max-width:2rem;" class="card-img-top align-self-center" alt="No img">
                </li>
                <li class="nav-item">
                    <img src="{%static 'flesh/svg/profile_masters.svg'%}" data-toggle="tab" href="#list-profile" style="max-width:2rem;" class="card-img-top align-self-center" alt="No img">
                </li>
            </ul>
        </div>
    </div>
</div>

<script  src="{% static 'cabinet/jquery-3.4.1/jquery-3.4.1.min.js' %}"></script>
<script  src="{% static 'cabinet/js/main_menu_one_OrderTab.js' %}"></script>
<script  src="{% static 'cabinet/js/scroll_1.js' %}"></script>
<script  src="{% static 'cabinet/js/scroll.js' %}"></script>
<script  src="{% static 'cabinet/js/ajax_prob.js' %}"></script>
<script>$('#content').load("{% url 'cabinet:timetable' %}?content=");</script>

{% endblock body %}
{% block footer %}
{% endblock footer %}